[package]
name = "doctest"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
ammonia = "3"
iron = "0.6"
maud = { path = "../maud", features = ["actix-web", "iron", "rocket"] }
pulldown-cmark = "0.8"
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "3045e0ac63fd5c4e2e543649c6871d896cbf9c0b" }
rouille = "3"

[lib]
path = "lib.rs"
